version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8088:9000"
    env_file:
      - .env.local
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    networks:
      - profilr_network
    command: ["bash", "/app/deploy/docker-entrypoint.development.sh"]

  redis:
    image: redis
    networks:
      - profilr_network
    ports:
      - "6380:6379"

networks:
  profilr_network:
    external: true
