FROM nginx:latest

COPY docker/nginx-default.template /etc/nginx/conf.d/default.template
COPY ./public /srv/web/public

CMD envsubst '$FASTCGI_PASS' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'