FROM debian:bullseye

# Copy the composer binary
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Add standard system tools (for composer)
RUN apt-get update \
 && apt-get install -y \
        nano \
        curl \
        zip \
        apt-transport-https \
        lsb-release \
        ca-certificates \
        wget \
        git

# Use packages from sury
RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
 && sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'

# Install php-fpm
RUN apt-get update \
 && apt-get install -y \
        php8.1-bcmath \
        php8.1-bz2 \
        php8.1-cli \
        php8.1-common \
        php8.1-curl \
        php8.1-fpm \
        php8.1-gd \
        php8.1-gmp \
        php8.1-intl \
        php8.1-mbstring \
        php8.1-opcache \
        php8.1-sqlite3 \
        php8.1-xml \
        php8.1-xmlrpc \
        php8.1-zip

# Copy config
COPY docker/phpfpm-php.ini /etc/php/8.1/fpm/php.ini
COPY docker/phpfpm-php-fpm.conf /etc/php/8.1/fpm/php-fpm.conf
COPY docker/phpfpm-www.conf /etc/php/8.1/fpm/pool.d/www.conf

# Create run directories
RUN mkdir /run/php/

# Copy application
COPY . /srv/web/

# Download dependencies
RUN cd /srv/web \
 && composer install --prefer-dist --no-dev --no-progress --no-suggest --no-ansi --no-scripts

# Change pwd
WORKDIR /srv/web

# Run application
CMD ["/srv/web/docker-phpfpm/entrypoint.sh"]
#CMD ["php-fpm7.4"]
